# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coord_ordinis_dense_cpp <- function(x, y, weights, lambda, penalty_factor, limits, nlambda, lmin_ratio, standardize, intercept, opts) {
    .Call(`_ordinis_coord_ordinis_dense_cpp`, x, y, weights, lambda, penalty_factor, limits, nlambda, lmin_ratio, standardize, intercept, opts)
}

